### ISSUE TITLE
one missing file in lecture template

### ISSUE THREAD

**Issue by zenzang** [dustinvtran/latex-templates#1]
Here I am really just a newbie in LaTex and have benefited a lot from these templates. Thanks! Just one small question, it seems some file is missing in your lecture template(https://github.com/dustinvtran/latex-templates/blob/master/lectures/main.tex#L3), could you update that? Also if it's not to much trouble, maybe also attach one of your lecture sample please? I think that would help people like me a lot.

**Comment by dustinvtran** [comment]
thanks for asking. i overhauled the `lectures/` directory and updated it to reflect many recent things i do now in latex (i haven't written lecture notes in a few years). it should compile now. 

let me know if you run into any additional troubles; happy to help.

**Comment by zenzang** [comment]
Thanks for the updating; very helpful!
