### ISSUE TITLE
references error in paper template

### ISSUE THREAD

**Issue by imnidhipatel** [dustinvtran/latex-templates#3]
BibTex not showing the references in the pdf file.

**Comment by dustinvtran** [comment]
Thanks for raising. What's the particular error? As you may know, references only appear if they're cited in the text.

**Comment by imnidhipatel** [comment]
Yes that is correct, but you can also use \nocite{*} for including the
reference.

**Comment by dustinvtran** [comment]
That can be useful sometimes. I generally only use references if they have context in the main text. Many conference/journal styles actually forbid \nocite{*} as some authors do quite a bit of self-citation with it.

**Comment by imnidhipatel** [comment]
Yes thats fine ! Will drop the issue :)
